language: python

python: 3.4

cache:
  pip: true
  directories:
    - target

script:
  - python syx5.py

deploy:
  provider: pages
  local_dir: target
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
