dist: xenial   # required for Python >= 3.7
language: python
python: 3.7

cache:
  # pip: true
  directories:
    - target

script:
  # - python -u 11-5.py
  # - python -u syx5.py
  # - python -u datacheck.py
  - python -u qhcjcc.py

deploy:
  provider: pages
  local_dir: target
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
